# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import replicate_pb2 as replicate__pb2


class ReplicateStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.synchronization = channel.unary_stream(
        '/Replicate/synchronization',
        request_serializer=replicate__pb2.Request_sync.SerializeToString,
        response_deserializer=replicate__pb2.Operation_sync.FromString,
        )
    self.put = channel.unary_unary(
        '/Replicate/put',
        request_serializer=replicate__pb2.Request.SerializeToString,
        response_deserializer=replicate__pb2.Response.FromString,
        )
    self.delete = channel.unary_unary(
        '/Replicate/delete',
        request_serializer=replicate__pb2.Request.SerializeToString,
        response_deserializer=replicate__pb2.Response.FromString,
        )


class ReplicateServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def synchronization(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def put(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def delete(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ReplicateServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'synchronization': grpc.unary_stream_rpc_method_handler(
          servicer.synchronization,
          request_deserializer=replicate__pb2.Request_sync.FromString,
          response_serializer=replicate__pb2.Operation_sync.SerializeToString,
      ),
      'put': grpc.unary_unary_rpc_method_handler(
          servicer.put,
          request_deserializer=replicate__pb2.Request.FromString,
          response_serializer=replicate__pb2.Response.SerializeToString,
      ),
      'delete': grpc.unary_unary_rpc_method_handler(
          servicer.delete,
          request_deserializer=replicate__pb2.Request.FromString,
          response_serializer=replicate__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Replicate', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
